spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.109.128/wimi_product
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
