spring:
  datasource:
    username: root
    password: 123
    #url: jdbc:mysql://192.168.109.128/wimi_product
    url: jdbc:mysql://127.0.0.1/wimi_product
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
